version: "3"

services:
  sportstore:
    build: .
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_DEVELOPMENT: "Production"
    depends_on:
      - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Secret@12345"
      ACCEPT_EULA: "Y"
